FROM python:3.12-slim

# To reduce the security risk
RUN apt-get update \
    && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*

# Define build arguments with default fallback values
ARG USER_UID=1000
ARG USER_GID=1000

# Create a non-root user and group
RUN groupadd -g $USER_GID celerygroup && \
    useradd -u $USER_UID -g celerygroup celeryuser

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the container
COPY --chown=celeryuser:celerygroup . /app

# Remove the workspace parameter and cellpose-kit mention
# RUN sed -i '/cellpose-kit = { workspace = true }/d' pyproject.toml \
#     && sed -i '/"cellpose-kit>=0.1.0",/d' pyproject.toml

# Upgrade pip and install the "uv" tool which manages the project
RUN pip install --upgrade pip && pip install uv

# Create a virtual environment using uv with Python 3.12
RUN uv venv --python 3.12

# "Activate" the venv for subsequent commands by updating PATH.
# This makes executables from the venv (like pip) available.
ENV PATH="/app/.venv/bin:$PATH"

# Install only the "celery-default" extra dependencies defined in pyproject file
RUN uv sync --package cp-server --extra celery-default --no-dev

# Give the celeryuser user ownership of the app and data directory
RUN chown celeryuser:celerygroup /app \
    && mkdir /data \
    && chown -R celeryuser:celerygroup /data

USER celeryuser

# CMD will be specified in docker-compose.yml for centralized management
