# Use the official Python 3.12.8 slim image
FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

# Define build arguments with default fallback values
ARG USER_UID=1000
ARG USER_GID=1000

# Create a non-root user and group
RUN groupadd -g $USER_GID celerygroup && \
    useradd -m -u $USER_UID -g celerygroup celeryuser

# Install required packages: software-properties-common to add PPAs, curl, and Python 3.12 along with its venv and distutils packages.
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get update && \
    apt-get install -y \
      python3.12 \
      python3.12-venv \
      curl && \
    rm -rf /var/lib/apt/lists/*

# Install pip for Python 3.12 using get-pip.py
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the container
COPY . /app

# Upgrade pip and install the "uv" tool which manages the project
RUN pip install --upgrade pip && pip install uv

# Create a virtual environment using uv with Python 3.12
RUN uv venv --python 3.12

# "Activate" the venv for subsequent commands by updating PATH.
# This makes executables from the venv (like pip) available.
ENV PATH="/app/.venv/bin:$PATH"

# Install only the "celery" extra dependencies defined in pyproject file
RUN uv pip install -r pyproject.toml --extra celery

# Give the celeryuser user ownership of the app and data directory
RUN chown -R celeryuser:celerygroup /app
RUN mkdir /data
RUN chown -R celeryuser:celerygroup /data
USER celeryuser

# Start the celery default worker
CMD ["watchmedo", "auto-restart", "--directory=/app/cp_server", "--pattern=*.py", "--recursive", "--", "celery", "-A", "cp_server.tasks_server.celery_app:celery_app", "worker", "-Q", "gpu_tasks", "--concurrency=10", "--loglevel=info"]