[project]
name = "cp-server"
version = "0.1.0"
description = "A FastAPI-based server for running Cellpose segmentation models. This server allows users to upload images, configure model settings, and receive segmented images as output. It supports GPU acceleration and various Cellpose model types."
readme = "README.md"
authors = [
    { name = "Benoit Roux", email = "benoit.roux@gmail.com" },
    { name = "Raphael Feurstein", email = "raphael.feurstein@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "celery>=5.4.0",
    "cellpose[gui]>=3.1.0",
    "fastapi[all]>=0.115.6",
    "redis>=5.2.1",
    "smo>=2.0.2",
]

[project.scripts]
cp-server = "cp_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "flask>=3.1.0",
    "pytest>=8.3.4",
]
